routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CharityController;
use App\Http\Controllers\CharityParticipantController;
use App\Http\Controllers\ProjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.welcome');
});

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('login', [AuthController::class, 'login'])->name('login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware('auth')->prefix('office')->name('admin.')->group(function () {

    Route::middleware('loggedin:superuser')->group(function () {

        Route::get('dashboard', function () {
            return view('admin.dashboard');
        })->name('dashboard');

        Route::resource('project', ProjectController::class);
    });

    Route::get('profile', function () {
        return view('admin.profile');
    })->name('profile');

    Route::resource('charity', CharityController::class);
    Route::resource('charity-participant', CharityParticipantController::class);

    Route::get('finance', function () {
        return view('admin.finance');
    })->name('finance');
});

resources/views/admin/charity.blade.php
<x-admin.layout :title="'Charity'">
    <div class="mt-5 gap-5 lg:flex xs:grid xs:grid-cols-1 xs:gap-5">
        <div class="lg:w-2/3 xs:span-col-1 h-full bg-white mb-4 p-4 shadow rounded-lg">
            <div class="mb-4">
                <h3 class="text-lg font-medium text-gray-900">
                    Timeline
                </h3>
                <p class="mt-1 text-sm text-gray-500">
                    All charity event shown in timeline below
                </p>
            </div>
            <x-admin.timeline :data="$data"></x-admin.timeline>
        </div>

        @if(Helper::isAllowed('superuser'))
        <div class="lg:w-1/3 xs:span-col-1 h-full bg-white p-4 shadow rounded-lg">
            <div class="mb-4">
                <h3 class="text-lg font-medium text-gray-900">
                    Create Charity
                </h3>
                <p class="mt-1 text-sm text-gray-500">
                    Fill the form below to create new charity event
                </p>
            </div>

            <form method="POST" action="{{route('admin.charity.store')}}">
                @csrf
                <x-admin.charity-form></x-admin.charity-form>
            </form>
        </div>
        @endif
    </div>

    @if(Helper::isAllowed('superuser'))
    <x-admin.modal-add-participant :user="$user"></x-admin.modal-add-participant>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.openParticipantModal').on('click', function(e){
                $('#participant-charity-id').val($(this).data("value"));
                $('#addParticipantModal').removeClass('invisible');
            });
            $('.closeParticipantModal').on('click', function(e){
                $('#addParticipantModal').addClass('invisible');
            });
        });
    </script>
    @endif

</x-admin.layout>

resources/views/admin/dashboard.blade.php
<x-admin.layout :title="'Dashboard'">
    <dl class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
        <div class="relative bg-white pt-5 px-4 pb-12 sm:pt-6 sm:px-6 shadow rounded-lg overflow-hidden">
            <dt>
                <div class="absolute bg-indigo-500 rounded-md p-3">
                    <!-- Heroicon name: outline/users -->
                    <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                </div>
                <p class="ml-16 text-sm font-medium text-gray-500 truncate">Total Subscribers</p>
            </dt>
            <dd class="ml-16 pb-6 flex items-baseline sm:pb-7">
                <p class="text-2xl font-semibold text-gray-900">
                    71,897
                </p>
                <p class="ml-2 flex items-baseline text-sm font-semibold text-green-600">
                    <!-- Heroicon name: solid/arrow-sm-up -->
                    <svg class="self-center flex-shrink-0 h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M5.293 9.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 7.414V15a1 1 0 11-2 0V7.414L6.707 9.707a1 1 0 01-1.414 0z"
                            clip-rule="evenodd" />
                    </svg>
                    <span class="sr-only">
                        Increased by
                    </span>
                    122
                </p>
                <div class="absolute bottom-0 inset-x-0 bg-gray-50 px-4 py-4 sm:px-6">
                    <div class="text-sm">
                        <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500"> View all<span
                                class="sr-only"> Total Subscribers stats</span></a>
                    </div>
                </div>
            </dd>
        </div>

        <div class="relative bg-white pt-5 px-4 pb-12 sm:pt-6 sm:px-6 shadow rounded-lg overflow-hidden">
            <dt>
                <div class="absolute bg-indigo-500 rounded-md p-3">
                    <!-- Heroicon name: outline/mail-open -->
                    <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M3 19v-8.93a2 2 0 01.89-1.664l7-4.666a2 2 0 012.22 0l7 4.666A2 2 0 0121 10.07V19M3 19a2 2 0 002 2h14a2 2 0 002-2M3 19l6.75-4.5M21 19l-6.75-4.5M3 10l6.75 4.5M21 10l-6.75 4.5m0 0l-1.14.76a2 2 0 01-2.22 0l-1.14-.76" />
                    </svg>
                </div>
                <p class="ml-16 text-sm font-medium text-gray-500 truncate">Avg. Open Rate</p>
            </dt>
            <dd class="ml-16 pb-6 flex items-baseline sm:pb-7">
                <p class="text-2xl font-semibold text-gray-900">
                    58.16%
                </p>
                <p class="ml-2 flex items-baseline text-sm font-semibold text-green-600">
                    <!-- Heroicon name: solid/arrow-sm-up -->
                    <svg class="self-center flex-shrink-0 h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M5.293 9.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 7.414V15a1 1 0 11-2 0V7.414L6.707 9.707a1 1 0 01-1.414 0z"
                            clip-rule="evenodd" />
                    </svg>
                    <span class="sr-only">
                        Increased by
                    </span>
                    5.4%
                </p>
                <div class="absolute bottom-0 inset-x-0 bg-gray-50 px-4 py-4 sm:px-6">
                    <div class="text-sm">
                        <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500"> View all<span
                                class="sr-only"> Avg. Open Rate stats</span></a>
                    </div>
                </div>
            </dd>
        </div>

        <div class="relative bg-white pt-5 px-4 pb-12 sm:pt-6 sm:px-6 shadow rounded-lg overflow-hidden">
            <dt>
                <div class="absolute bg-indigo-500 rounded-md p-3">
                    <!-- Heroicon name: outline/cursor-click -->
                    <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M15 15l-2 5L9 9l11 4-5 2zm0 0l5 5M7.188 2.239l.777 2.897M5.136 7.965l-2.898-.777M13.95 4.05l-2.122 2.122m-5.657 5.656l-2.12 2.122" />
                    </svg>
                </div>
                <p class="ml-16 text-sm font-medium text-gray-500 truncate">Avg. Click Rate</p>
            </dt>
            <dd class="ml-16 pb-6 flex items-baseline sm:pb-7">
                <p class="text-2xl font-semibold text-gray-900">
                    24.57%
                </p>
                <p class="ml-2 flex items-baseline text-sm font-semibold text-red-600">
                    <!-- Heroicon name: solid/arrow-sm-down -->
                    <svg class="self-center flex-shrink-0 h-5 w-5 text-red-500" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M14.707 10.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 12.586V5a1 1 0 012 0v7.586l2.293-2.293a1 1 0 011.414 0z"
                            clip-rule="evenodd" />
                    </svg>
                    <span class="sr-only">
                        Decreased by
                    </span>
                    3.2%
                </p>
                <div class="absolute bottom-0 inset-x-0 bg-gray-50 px-4 py-4 sm:px-6">
                    <div class="text-sm">
                        <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500"> View all<span
                                class="sr-only"> Avg. Click Rate stats</span></a>
                    </div>
                </div>
            </dd>
        </div>

        <div class="relative bg-white pt-5 px-4 pb-12 sm:pt-6 sm:px-6 shadow rounded-lg overflow-hidden">
            <dt>
                <div class="absolute bg-indigo-500 rounded-md p-3">
                    <!-- Heroicon name: outline/cursor-click -->
                    <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M15 15l-2 5L9 9l11 4-5 2zm0 0l5 5M7.188 2.239l.777 2.897M5.136 7.965l-2.898-.777M13.95 4.05l-2.122 2.122m-5.657 5.656l-2.12 2.122" />
                    </svg>
                </div>
                <p class="ml-16 text-sm font-medium text-gray-500 truncate">Avg. Click Rate</p>
            </dt>
            <dd class="ml-16 pb-6 flex items-baseline sm:pb-7">
                <p class="text-2xl font-semibold text-gray-900">
                    24.57%
                </p>
                <p class="ml-2 flex items-baseline text-sm font-semibold text-red-600">
                    <!-- Heroicon name: solid/arrow-sm-down -->
                    <svg class="self-center flex-shrink-0 h-5 w-5 text-red-500" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M14.707 10.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 12.586V5a1 1 0 012 0v7.586l2.293-2.293a1 1 0 011.414 0z"
                            clip-rule="evenodd" />
                    </svg>
                    <span class="sr-only">
                        Decreased by
                    </span>
                    3.2%
                </p>
                <div class="absolute bottom-0 inset-x-0 bg-gray-50 px-4 py-4 sm:px-6">
                    <div class="text-sm">
                        <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500"> View all<span
                                class="sr-only"> Avg. Click Rate stats</span></a>
                    </div>
                </div>
            </dd>
        </div>
    </dl>
</x-admin.layout>

resources/views/admin/finance.blade.php
<x-admin.layout :title="'Finance'">
    <div class="py-4">
        <div class="border-4 border-dashed border-gray-200 rounded-lg h-96"></div>
    </div>
</x-admin.layout>

resources/views/admin/profile.blade.php
<x-admin.layout :title="'Profile'">
    <article class="bg-white pb-6 lg:col-span-2 shadow rounded-lg">
        <!-- Profile header -->
        <div>
            <div>
                <img class="h-32 w-full object-cover lg:h-48"
                    src="https://images.unsplash.com/photo-1444628838545-ac4016a5418a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"
                    alt="">
            </div>
            <div class="max-w-3xl px-4 sm:px-6 lg:px-8">
                <div class="-mt-12 sm:-mt-16 sm:flex sm:items-end sm:space-x-5">
                    <div class="flex">
                        @if(Auth::user()->photo)
                        <img class="h-24 w-24 rounded-full ring-4 ring-white sm:h-32 sm:w-32"
                            src="https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80"
                            alt="">
                        @else
                        <span
                            class="inline-flex items-center justify-center h-24 w-24 sm:h-32 sm:w-32 rounded-full bg-blue-500 ">
                            <span class="text-3xl font-medium leading-none text-white">{{
                                Helper::getNameInitial(Auth::user()->name)
                                }}</span>
                        </span>
                        @endif
                    </div>
                    <div class="mt-6 sm:flex-1 sm:min-w-0 sm:flex sm:items-center sm:justify-end sm:space-x-6 sm:pb-1">
                        <div class="sm:hidden 2xl:block mt-6 min-w-0 flex-1">
                            <h1 class="text-2xl font-bold text-gray-900 truncate">
                                {{ Auth::user()->name }}
                            </h1>
                        </div>
                    </div>
                    <button type="button"
                        class="inline-flex justify-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500">
                        <!-- Heroicon name: solid/pencil -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 -ml-1 mr-2 h-5 w-5 text-gray-400"
                            viewBox="0 0 20 20" fill="currentColor">
                            <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z" />
                            <path fill-rule="evenodd"
                                d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"
                                clip-rule="evenodd" />
                        </svg>
                        <span>Edit Profile</span>
                    </button>
                </div>
                <div class="hidden sm:block 2xl:hidden mt-6 min-w-0 flex-1">
                    <h1 class="text-2xl font-bold text-gray-900 truncate">
                        {{ Auth::user()->name }}
                    </h1>
                </div>
            </div>
        </div>

        <div class="xl:grid xl:grid-cols-2">
            <!-- Description list -->
            <div class="mt-6 px-4 sm:px-6 lg:px-8">
                <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
                    <div class="sm:col-span-1">
                        <dt class="text-sm font-medium text-gray-500">
                            Name
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900">
                            {{ Auth::user()->name }}
                        </dd>
                    </div>

                    <div class="sm:col-span-1">
                        <dt class="text-sm font-medium text-gray-500">
                            Username
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900">
                            {{ Auth::user()->username }}
                        </dd>
                    </div>

                    <div class="sm:col-span-2">
                        <dt class="text-sm font-medium text-gray-500">
                            About
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 space-y-5">
                            <p>Tincidunt quam neque in cursus viverra orci, dapibus nec tristique. Nullam ut sit dolor
                                consectetur urna, dui cras nec sed. Cursus risus congue arcu aenean posuere aliquam.</p>
                            <p>Et vivamus lorem pulvinar nascetur non. Pulvinar a sed platea rhoncus ac mauris amet.
                                Urna,
                                sem pretium sit pretium urna, senectus vitae. Scelerisque fermentum, cursus felis dui
                                suspendisse velit pharetra. Augue et duis cursus maecenas eget quam lectus. Accumsan
                                vitae
                                nascetur pharetra rhoncus praesent dictum risus suspendisse.</p>
                        </dd>
                    </div>
                </dl>
            </div>

            <!-- Description list -->
            <div class="mt-6 px-4 sm:px-6 lg:px-8">
                <ul role="list" class="grid grid-cols-1 gap-5 sm:gap-6 sm:grid-cols-2 lg:grid-cols-2">
                    <li class="col-span-1 flex shadow-sm rounded-md">
                        <div
                            class="flex-shrink-0 flex items-center justify-center w-16 bg-blue-600 text-white text-sm font-medium rounded-l-md">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                            </svg>
                        </div>
                        <div
                            class="flex-1 flex items-center justify-between border-t border-r border-b border-gray-200 bg-white rounded-r-md truncate">
                            <div class="flex-1 px-4 py-2 text-sm truncate">
                                <a href="#" class="text-gray-900 font-medium hover:text-gray-600">Joined Since</a>
                                <p class="text-gray-500">January, 1st 2020</p>
                            </div>
                        </div>
                    </li>
                    <li class="col-span-1 flex shadow-sm rounded-md">
                        <div
                            class="flex-shrink-0 flex items-center justify-center w-16 bg-green-600 text-white text-sm font-medium rounded-l-md">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
                            </svg>
                        </div>
                        <div
                            class="flex-1 flex items-center justify-between border-t border-r border-b border-gray-200 bg-white rounded-r-md truncate">
                            <div class="flex-1 px-4 py-2 text-sm truncate">
                                <a href="#" class="text-gray-900 font-medium hover:text-gray-600">Donate</a>
                                <p class="text-gray-500">Rp 10.000.000,00</p>
                            </div>
                        </div>
                    </li>
                    <li class="col-span-1 flex shadow-sm rounded-md">
                        <div
                            class="flex-shrink-0 flex items-center justify-center w-16 bg-gray-400 text-white text-sm font-medium rounded-l-md">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path d="M9 17a2 2 0 11-4 0 2 2 0 014 0zM19 17a2 2 0 11-4 0 2 2 0 014 0z" />
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M13 16V6a1 1 0 00-1-1H4a1 1 0 00-1 1v10a1 1 0 001 1h1m8-1a1 1 0 01-1 1H9m4-1V8a1 1 0 011-1h2.586a1 1 0 01.707.293l3.414 3.414a1 1 0 01.293.707V16a1 1 0 01-1 1h-1m-6-1a1 1 0 001 1h1M5 17a2 2 0 104 0m-4 0a2 2 0 114 0m6 0a2 2 0 104 0m-4 0a2 2 0 114 0" />
                            </svg>
                        </div>
                        <div
                            class="flex-1 flex items-center justify-between border-t border-r border-b border-gray-200 bg-white rounded-r-md truncate">
                            <div class="flex-1 px-4 py-2 text-sm truncate">
                                <a href="#" class="text-gray-900 font-medium hover:text-gray-600">Event Joined</a>
                                <p class="text-gray-500">5 events</p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </article>
</x-admin.layout>

resources/views/admin/project.blade.php
<x-admin.layout :title="'Project'">
    <div class="py-4">
        <div class="border-4 border-dashed border-gray-200 rounded-lg h-96"></div>
    </div>
</x-admin.layout>